employeeData = [
    {
        "id": "91F08N",
        "lname": "Cao Ly",
        "fname": "Đăng",
        "role": "backofficer",
        "phone": "405038488",
        "address": "Nha Trang",
        "state": "sẵn sàng",
    },
    {
        "id": "XM00N0",
        "lname": "Cao Ly",
        "fname": "Đăng",
        "role": "backofficer",
        "phone": "768588099",
        "address": "Đà Lạt",
        "state": "sẵn sàng",
    },
    {
        "id": "6O7K8V",
        "lname": "Cao Ly",
        "fname": "Đăng",
        "role": "backofficer",
        "phone": "836120420",
        "address": "Đà Lạt",
        "state": "sẵn sàng",
    },
    {
        "id": "TONUWH",
        "lname": "Cao Ly",
        "fname": "Đăng",
        "role": "backofficer",
        "phone": "124646919",
        "address": "Đà Lạt",
        "state": "sẵn sàng",
    },
    {
        "id": "P3QJO9",
        "lname": "Cao Ly",
        "fname": "Đăng",
        "role": "backofficer",
        "phone": "154702177",
        "address": "Đà Lạt",
        "state": "sẵn sàng",
    },
    {
        "id": "HRFUN5",
        "lname": "Cao Ly",
        "fname": "Đăng",
        "role": "backofficer",
        "phone": "631312216",
        "address": "Đà Lạt",
        "state": "sẵn sàng",
    },
    {
        "id": "5WYNF9",
        "lname": "Ly Quý",
        "fname": "Ngõ",
        "role": "janitor",
        "phone": "677376924",
        "address": "Đà Lạt",
        "state": "sẵn sàng",
    },
    {
        "id": "8HWATJ",
        "lname": "Ly Quý",
        "fname": "Ngõ",
        "role": "janitor",
        "phone": "662779430",
        "address": "Đà Lạt",
        "state": "sẵn sàng",
    },
    {
        "id": "UHCKOL",
        "lname": "Ly Quý",
        "fname": "Ngõ",
        "role": "janitor",
        "phone": "384260881",
        "address": "Đà Lạt",
        "state": "sẵn sàng",
    },
    {
        "id": "N8EBS2",
        "lname": "Ly Quý",
        "fname": "Ngõ",
        "role": "janitor",
        "phone": "437561096",
        "address": "Đà Lạt",
        "state": "sẵn sàng",
    },
    {
        "id": "BZKTL6",
        "lname": "Cao Ly",
        "fname": "Đăng",
        "role": "janitor",
        "phone": "87235734",
        "address": "Đà Lạt",
        "state": "sẵn sàng",
    },
    {
        "id": "WIEWZY",
        "lname": "Cao Ly",
        "fname": "Đăng",
        "role": "janitor",
        "phone": "240547493",
        "address": "Đà Lạt",
        "state": "sẵn sàng",
    },
    {
        "id": "PUPLES",
        "lname": "Ngô Quy",
        "fname": "Nho",
        "role": "janitor",
        "phone": "205765808",
        "address": "Đà Lạt",
        "state": "sẵn sàng",
    },
    {
        "id": "X3R5KJ",
        "lname": "Ngô Quy",
        "fname": "Nho",
        "role": "janitor",
        "phone": "627847975",
        "address": "Bình Dương",
        "state": "sẵn sàng",
    },
    {
        "id": "3USZDO",
        "lname": "Ngô Quy",
        "fname": "Nho",
        "role": "janitor",
        "phone": "209252677",
        "address": "Bình Dương",
        "state": "sẵn sàng",
    },
    {
        "id": "8PYLK9",
        "lname": "Ngô Quy",
        "fname": "Nho",
        "role": "janitor",
        "phone": "901275808",
        "address": "Bình Dương",
        "state": "sẵn sàng",
    },
    {
        "id": "1XQL4O",
        "lname": "Ngô Quy",
        "fname": "Nho",
        "role": "janitor",
        "phone": "900219439",
        "address": "Bình Dương",
        "state": "sẵn sàng",
    },
    {
        "id": "L0SXYE",
        "lname": "Cao Ly",
        "fname": "Đăng",
        "role": "janitor",
        "phone": "246846354",
        "address": "Bình Dương",
        "state": "sẵn sàng",
    },
    {
        "id": "LO718R",
        "lname": "Ngô Quý",
        "fname": "Liên",
        "role": "janitor",
        "phone": "132301896",
        "address": "Bình Dương",
        "state": "sẵn sàng",
    },
    {
        "id": "FH7TG4",
        "lname": "Ngô Quý",
        "fname": "Liên",
        "role": "janitor",
        "phone": "73598097",
        "address": "Bình Dương",
        "state": "sẵn sàng",
    },
    {
        "id": "P2DE1X",
        "lname": "Ngô Quý",
        "fname": "Liên",
        "role": "janitor",
        "phone": "343386762",
        "address": "Bình Dương",
        "state": "sẵn sàng",
    },
    {
        "id": "43RHQS",
        "lname": "Ngô Quý",
        "fname": "Liên",
        "role": "janitor",
        "phone": "23716920",
        "address": "Bình Dương",
        "state": "sẵn sàng",
    },
    {
        "id": "2HO8KW",
        "lname": "Ngô Quý",
        "fname": "Liên",
        "role": "janitor",
        "phone": "456596824",
        "address": "Bình Dương",
        "state": "sẵn sàng",
    },
    {
        "id": "IXAQ3W",
        "lname": "Ngô Quý",
        "fname": "Liên",
        "role": "janitor",
        "phone": "148475904",
        "address": "Bình Dương",
        "state": "sẵn sàng",
    },
    {
        "id": "27NFCA",
        "lname": "Ngô Quý",
        "fname": "Liên",
        "role": "janitor",
        "phone": "425635286",
        "address": "Bình Dương",
        "state": "sẵn sàng",
    },
    {
        "id": "1K5T64",
        "lname": "Ngô Quý",
        "fname": "Liên",
        "role": "janitor",
        "phone": "91080624",
        "address": "Bình Dương",
        "state": "sẵn sàng",
    },
    {
        "id": "F63RNX",
        "lname": "Đặng Hồng",
        "fname": "Thảo",
        "role": "janitor",
        "phone": "821337260",
        "address": "TP HCM",
        "state": "sẵn sàng",
    },
    {
        "id": "QKBGBB",
        "lname": "Đặng Hồng",
        "fname": "Thảo",
        "role": "janitor",
        "phone": "9273501",
        "address": "TP HCM",
        "state": "sẵn sàng",
    },
    {
        "id": "C70FSZ",
        "lname": "Đặng Hồng",
        "fname": "Thảo",
        "role": "janitor",
        "phone": "213289751",
        "address": "TP HCM",
        "state": "sẵn sàng",
    },
    {
        "id": "RHXI48",
        "lname": "Đặng Hồng",
        "fname": "Thảo",
        "role": "janitor",
        "phone": "959130774",
        "address": "TP HCM",
        "state": "sẵn sàng",
    },
    {
        "id": "QOFL54",
        "lname": "Đặng Hồng",
        "fname": "Thảo",
        "role": "janitor",
        "phone": "415925906",
        "address": "TP HCM",
        "state": "sẵn sàng",
    },
    {
        "id": "QYCVCQ",
        "lname": "Đặng Hồng",
        "fname": "Thảo",
        "role": "janitor",
        "phone": "134731580",
        "address": "TP HCM",
        "state": "sẵn sàng",
    },
    {
        "id": "MDJG6W",
        "lname": "Đặng Hồng",
        "fname": "Thảo",
        "role": "janitor",
        "phone": "302386731",
        "address": "TP HCM",
        "state": "sẵn sàng",
    },
    {
        "id": "QZIUW3",
        "lname": "Kha Mạnh",
        "fname": "Nghĩa",
        "role": "janitor",
        "phone": "988724908",
        "address": "TP HCM",
        "state": "sẵn sàng",
    },
    {
        "id": "3XUVV6",
        "lname": "Kha Mạnh",
        "fname": "Nghĩa",
        "role": "janitor",
        "phone": "786011956",
        "address": "TP HCM",
        "state": "sẵn sàng",
    },
    {
        "id": "O27A42",
        "lname": "Kha Mạnh",
        "fname": "Nghĩa",
        "role": "collector",
        "phone": "641670921",
        "address": "TP HCM",
        "state": "sẵn sàng",
    },
    {
        "id": "BP7I7J",
        "lname": "Kha Mạnh",
        "fname": "Nghĩa",
        "role": "collector",
        "phone": "161894552",
        "address": "TP HCM",
        "state": "sẵn sàng",
    },
    {
        "id": "BYQPNV",
        "lname": "Kha Mạnh",
        "fname": "Nghĩa",
        "role": "collector",
        "phone": "786079012",
        "address": "TP HCM",
        "state": "sẵn sàng",
    },
    {
        "id": "W8KIX4",
        "lname": "Kha Mạnh",
        "fname": "Nghĩa",
        "role": "collector",
        "phone": "358545965",
        "address": "TP HCM",
        "state": "sẵn sàng",
    },
    {
        "id": "NRTKSH",
        "lname": "Kha Mạnh",
        "fname": "Nghĩa",
        "role": "collector",
        "phone": "238899273",
        "address": "TP HCM",
        "state": "sẵn sàng",
    },
    {
        "id": "XRGPOR",
        "lname": "Kha Mạnh",
        "fname": "Nghĩa",
        "role": "collector",
        "phone": "472278174",
        "address": "TP HCM",
        "state": "sẵn sàng",
    },
    {
        "id": "BTVJF7",
        "lname": "Kha Mạnh",
        "fname": "Nghĩa",
        "role": "collector",
        "phone": "645984339",
        "address": "TP HCM",
        "state": "sẵn sàng",
    },
    {
        "id": "DW5ZN4",
        "lname": "Kha Mạnh",
        "fname": "Nghĩa",
        "role": "collector",
        "phone": "481295956",
        "address": "TP HCM",
        "state": "sẵn sàng",
    },
    {
        "id": "AEM4RN",
        "lname": "Kha Mạnh",
        "fname": "Nghĩa",
        "role": "collector",
        "phone": "132637395",
        "address": "TP HCM",
        "state": "sẵn sàng",
    },
    {
        "id": "3UHNI7",
        "lname": "Cao Ly",
        "fname": "Đăng",
        "role": "collector",
        "phone": "596643573",
        "address": "TP HCM",
        "state": "sẵn sàng",
    },
    {
        "id": "P399ID",
        "lname": "Cao Ly",
        "fname": "Đăng",
        "role": "collector",
        "phone": "192513241",
        "address": "TP HCM",
        "state": "sẵn sàng",
    },
    {
        "id": "5GPO80",
        "lname": "Cao Ly",
        "fname": "Đăng",
        "role": "collector",
        "phone": "110771967",
        "address": "TP HCM",
        "state": "sẵn sàng",
    },
    {
        "id": "VUEMV6",
        "lname": "Cao Ly",
        "fname": "Đăng",
        "role": "collector",
        "phone": "701422506",
        "address": "TP HCM",
        "state": "sẵn sàng",
    },
    {
        "id": "9HG4PA",
        "lname": "Cao Ly",
        "fname": "Đăng",
        "role": "collector",
        "phone": "413237897",
        "address": "TP HCM",
        "state": "sẵn sàng",
    },
    {
        "id": "O9TKEQ",
        "lname": "Cao Ly",
        "fname": "Đăng",
        "role": "collector",
        "phone": "746433804",
        "address": "TP HCM",
        "state": "sẵn sàng",
    },
]
